#!/bin/sh
export USER="haobp"
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/bin/X11"
NAME=vncstart

start()
{
	su $USER -c"vncserver -depth 24 -geometry 1440x840"
}

stop()
{
	su $USER -c"vncserver -kill :1"
}

case $1 in
	start)
		echo -n "Starting Xvnc: "
		start
		;;
	stop)
		echo -n "Starting Xvnc: "
		stop	
		;;
	restart)
        echo -n "Restarting Xvnc "
		stop
		start
		;;
	*)
		echo "Usage: /etc/init.d/$NAME {start|stop|restart}"
		exit 1
		;;
esac
exit 0
